#
# Makefile for misc devices that really don't fit anywhere else.
#

obj-$(CONFIG_VIBRATOR_HANBACK)  += vibrator.o
obj-$(CONFIG_PROXIMITY_SENSOR)	+= proximity.o
obj-$(CONFIG_LED)	+= led.o
obj-$(CONFIG_TEXT_LCD)	+= textlcd.o
obj-$(CONFIG_7_SEGMENT)	+= segment.o
obj-$(CONFIG_DOT_MATRIX)	+= dotmatrix.o
obj-$(CONFIG_DIP_SWITCH)	+= dipsw.o
obj-$(CONFIG_PIEZO)	+= piezo.o
obj-$(CONFIG_FULL_COLOR_LED)	+= fullcolorled.o
obj-$(CONFIG_OLED)	+= oled.o
obj-$(CONFIG_BASELED)	+= baseled.o
obj-$(CONFIG_BASESEG)	+= baseseg.o
